### ISSUE TITLE
adding a private chatroom function 

### ISSUE THREAD

**Issue by HuaYangttt** [The-Powerpuff-Girls3/CSC-510-Movie-Mood#1]
Description
We need to implement a private chatroom feature that allows users to engage in one-on-one or small group conversations that are not visible to the public. This function is intended to enhance privacy and improve user experience by providing a secure space for private discussions.

Requirements
User Authentication:

Ensure that only authenticated users can create or join private chatrooms.
Room Creation:

Users should be able to create private chatrooms with customizable room names.
A password or invite-only mechanism should be implemented for accessing the room.
User Invitations:

Provide an option to invite specific users to the private chatroom.
Allow for the invitation of users via email or username.
Message Privacy:

Messages exchanged within the private chatroom should be end-to-end encrypted to ensure security and privacy.
Notification System:

Users should receive notifications for new messages within the private chatrooms they belong to.
UI/UX:

The chatroom interface should be user-friendly and intuitive.
Include options to mute, archive, or delete private chatrooms.
Logging:

For security reasons, basic logging (without message content) should be implemented to track who creates, joins, and leaves private chatrooms.
Additional Considerations
Integration with the existing public chatroom system should be smooth.
Compatibility with mobile and desktop platforms.
Scalability of the system to support a growing number of users.
Acceptance Criteria
Private chatrooms can be successfully created and accessed by invited users.
Message privacy is ensured, and only invited users can participate in the conversation.
Notifications work seamlessly for new messages.
The system performs efficiently under a growing user base.

**Comment by HuaYangttt** [comment]
assign to @HuaYangttt

**Comment by lvxuntao** [comment]
The description provides a comprehensive plan for implementing a private chatroom feature, emphasizing user privacy and a positive experience. Key requirements like user authentication, message encryption, and a user-friendly interface are well articulated. However, including specific metrics for success and addressing potential implementation challenges could enhance the plan's effectiveness. Overall, it’s a solid foundation for developing a secure communication tool.
