### ISSUE TITLE
test case failure: Fails when Test multiple tags with both defined and undefined genres

### ISSUE THREAD

**Issue by lvxuntao** [The-Powerpuff-Girls3/CSC-510-Movie-Mood#4]
Among the 20 test cases, there is 1 failure:

### FAIL: test_create_colored_tags_multiple (__main__.Tests)
**Test case 7:** Test multiple tags with both defined and undefined genres  
----------------------------------------------------------------------  
**Traceback (most recent call last):**  
  File "D:\git\CSC-510-Movie-Mood\app\test\test_new.py", line 43, in `test_create_colored_tags_multiple`  
    self.assertEqual(result, expected_result)  
**AssertionError:** '<spa[47 chars]FFF;             padding: 5px; border-radius: [256 chars]pan>' != '<spa[47 chars]FFF; padding: 5px; border-radius: 5px;">Musica[220 chars]pan>'  
Diff is 685 characters long. Set `self.maxDiff` to None to see it.

**Comment by lvxuntao** [comment]
We want to ensure that the create_colored_tags function raises an exception when it receives invalid input. So we can add input validation at the start of the function to confirm that the input is a list of strings.

The code add at the start of the function:
    if not isinstance(genres, list) or not all(isinstance(genre, str) for genre in genres):
        raise ValueError("Input must be a list of strings representing genres.")

**Comment by YinanWusoymilk** [comment]
It looks ok to me now!!! thanks for your contribution!!!!!!!

**Comment by lvxuntao** [comment]
The issue is solved now
