### ISSUE TITLE
testing case: SyntaxError: unterminated string literal (detected at line 69)

### ISSUE THREAD

**Issue by YinanWusoymilk** [The-Powerpuff-Girls3/CSC-510-Movie-Mood#8]
Hi, there is something wrong about the series page when running the test case

(.venv) PS F:\course work\510 se\CSC-510-Movie-Mood\app\test> python -m unittest test_series.py
>>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\3.12python\Lib\unittest\__main__.py", line 18, in <module>
    main(module=None)
  File "D:\3.12python\Lib\unittest\main.py", line 104, in __init__
    self.parseArgs(argv)
  File "D:\3.12python\Lib\unittest\main.py", line 153, in parseArgs
    self.createTests()
  File "D:\3.12python\Lib\unittest\main.py", line 164, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\3.12python\Lib\unittest\loader.py", line 207, in 
loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name 
in names]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\3.12python\Lib\unittest\loader.py", line 137, in 
loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\course work\510 se\CSC-510-Movie-Mood\app\test\test_series.py", line 69
    alert_div = self.soup.find('div', class_="
                                             ^
SyntaxError: unterminated string literal (detected at line 69)
(.venv) PS F:\course work\510 se\CSC-510-Movie-Mood\app\test>

**Comment by YinanWusoymilk** [comment]
omg sorry to cause this bug

this is identified as in new_series.html

the tag is wrong <h2><center>📺 Today's Series Coming Soon! 📺</center></h3>

instead it should be <h2><center>📺 Today's Series Coming Soon! 📺</center></h2>

I have fixed this and uploaded that, thanks for sharing this

**Comment by lvxuntao** [comment]
I can not see the code. It seems okay to me!

**Comment by YinanWusoymilk** [comment]
sorry for the confusion!!!!

what I'm trying to say is that the first line of tag is <h2><h3> which is wrong

we need to keep it consistent by <h2><h2>

**Comment by YinanWusoymilk** [comment]
sorry for the confusion!!!!

what I'm trying to say is that the first line of tag is h2 h3

which is wrong
we need to keep it consistent by h2 h2

**Comment by YinanWusoymilk** [comment]
This issue is closed now
